apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  infrastructureTemplate:
    apiVersion: cluster-api-provider-hcloud.capihc.com/v1beta1
    kind: HcloudMachineTemplate
    name: {{ .Values.cluster.name }}-control-plane-mt-{{ .Values.controlPlanes.machineTemplate.version }}
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          {{- with .Values.controlPlanes.server.nodeLabels }}
          node-labels: node-access=ssh,capihc.com/cpu={{ .cpu }},{{ .customLabels }}
          {{- end }}
    useExperimentalRetryJoin: {{ .Values.controlPlanes.kubeadmConfig.useExperimentalRetryJoin }}
    verbosity: {{ .Values.controlPlanes.kubeadmConfig.verbosity }}
  replicas: {{ .Values.controlPlanes.server.replicas }}
  version: {{ .Values.cluster.kubernetesVersion }}